apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-test
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: infra
      server: <url_controlplane>
  sourceRepos:
    - https://gitlab.com/minha_empresa/application-manifests.git
    - https://helm.releases.hashicorp.com