apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: sistemas
spec:
  generators:
    - git:
        repoURL: https://github.com/marcelo-luizz/gitops-infra.git
        revision: HEAD
        directories:
          - path: environments/devops-labs/applications
  template:
    metadata:
      name: '{{.path.basename}}-app'
    spec:
      project: gke-platform-engineering
      source:
        repoURL: https://github.com/marcelo-luizz/gitops-infra.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: 'gke-platform-engineering'
#        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
