apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-devops-labs
  namespace: sistemas # Onde a Application será criada no cluster devops
spec:
  project: gke-platform-engineering
  source:
    repoURL: https://charts.external-secrets.io # Repositório do Helm chart
    targetRevision: 0.9.17
    chart: external-secrets
    helm:
      valueFiles:
        - values.yaml # Values específicos do ambiente
  destination:
    name: gke-platform-engineering # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: external-secrets # Namespace onde o external-secrets será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
