apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-devops-labs
  namespace: argocd # Onde a Application será criada no cluster devops
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io # Repositório do Helm chart
    targetRevision: v1.14.4
    chart: cert-manager
    helm:
      valueFiles:
        - $values/environments/devops-labs/cluster-config/tools/cert-manager/values.yaml # Values específicos do ambiente
  destination:
    name: devops-labs-cluster # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: cert-manager # Namespace onde o cert-manager será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
