apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-platform-engineering
  namespace: sistemas # Onde a Application será criada no cluster devops
spec:
  project: gke-platform-engineering
  source:
    repoURL: https://charts.jetstack.io # Repositório do Helm chart
    targetRevision: v1.14.4
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml # Values específicos do ambiente
  destination:
    name: gke-platform-engineering # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: cert-manager # Namespace onde o cert-manager será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
