apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-platform-engineering
  namespace: sistemas # Onde a Application será criada no cluster devops
spec:
  project: gke-platform-engineering
  source:
    repoURL: https://github.com/marcelo-luizz/gitops-infra.git # Repositório do Helm chart
    targetRevision: HEAD
    path: environments/devops-labs/cluster-config/manifests/deployments/nginx-example
  destination:
    name: https://34.95.151.58 # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: nginx # Namespace onde o cert-manager será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
