apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-devops-labs
  namespace: default # Onde a Application será criada no cluster devops
spec:
  project: default
  source:
    repoURL: https://github.com/marcelo-luizz/gitops-infra.git # Repositório do Helm chart
    targetRevision: HEAD
    path: environments/devops-labs/cluster-config/manifests/deployments/test2
  destination:
    name: devops-labs-cluster # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: nginx # Namespace onde o cert-manager será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
