apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-integration
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    chart: argo-rollouts
    targetRevision: 2.31.0
    helm:
      parameters:
        - name: installCRDs
          value: "true" 
        - name: metrics.enabled
          value: "true" 
        - name: metrics.serviceMonitor.enabled
          value: "true" 
        - name: controller.replicas
          value: "2" 
        # - name: controller.serviceAccount.create
        #   value: "true"
        # - name: controller.serviceAccount.name
        #   value: "argo-rollouts-controller" # Nome da ServiceAccount
  destination:
    name: in-cluster
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
