apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts-integration
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: gke-platform-engineering
  source:
    repoURL: https://argoproj.github.io/argo-helm 
    chart: argo-rollouts
    targetRevision: 2.31.0
    helm:
      parameters:
        - name: metrics.enabled
          value: "true" 
        - name: dashboard.enabled
          value: "true"

  destination:
    name: gke-platform-engineering
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
