apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-platform-engineering
  namespace: sistemas # Onde a Application será criada no cluster devops
spec:
  project: gke-platform-engineering
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
 # Repositório do Helm chart
    targetRevision: 27.20.1
    chart: prometheus
    helm:
      valueFiles:
        - values.yaml # Values específicos do ambiente
  destination:
    name: gke-platform-engineering # Exemplo: 'dev-cluster', 'int-cluster', 'pre-prod-cluster', 'prod-cluster'
    namespace: prometheus # Namespace onde o external-secrets será instalado no cluster de destino
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      platform-engineering
