apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-environments-apps
  namespace: default
spec:
  generators:
    - git:
        repoURL: https://github.com/marcelo-luizz/gitops-infra.git
        revision: HEAD
        directories:
          - path: environments/*
  template:
    metadata:
      name: 'cluster-devops-labs'
    spec:
      project: default
      source:
        repoURL: https://github.com/marcelo-luizz/gitops-infra.git
        targetRevision: HEAD
        path: environments/{{path.basename}}/cluster-config
      destination:
        name: 'devops-labs-cluster'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
